import type { Metadata } from "next";
import "./globals.css";
import HeaderDashboard from "@/components/Dashboard/TopNav";
import { SidebarDemo } from "@/components/Dashboard/SideBar";
import  { RightSidebar } from "@/components/Dashboard/RightSideBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        {children}
      </body>
    </html>
  );
}